#!/bin/sh /etc/rc.common

USE_PROCD=1
START=99

NAME="garuda"
PROG="/usr/bin/garuda-agent"

start_service() {
        procd_open_instance "$NAME"
        procd_set_param command "$PROG"
        procd_set_param file "/etc/garuda/garuda.conf"

        procd_set_param stdout 1
        procd_set_param stderr 1
        procd_set_param respawn

        procd_close_instance
}

reload_service() {
        stop
        start
}

service_triggers() {
        procd_add_reload_trigger "$NAME"
}
