#!/bin/sh /etc/rc.common

USE_PROCD=1
START=99

NAME="xray"
PROG="/usr/bin/xray"

start_service() {
        procd_open_instance "$NAME"
        procd_set_param command "$PROG" run
        procd_append_param command -confdir "/etc/xray"
        procd_append_param command -config "/etc/xray/config.json"
        procd_append_param command -format "json"
        procd_set_param env XRAY_LOCATION_ASSET="/usr/share/xray"
        procd_set_param file "/etc/xray/config.json"

        procd_set_param limits core="unlimited"
        procd_set_param limits nofile="1000000 1000000"
        procd_set_param stdout 1
        procd_set_param stderr 1
        procd_set_param respawn

        procd_close_instance
}

reload_service() {
        stop
        start
}

service_triggers() {
        procd_add_reload_trigger "$NAME"
}